In [30]:
import pandas as pd
import altair as alt
archivo = "charts_latam_carol_6m.csv"

df = pd.read_csv(archivo)

df.head()

,pais,fecha,mes_muestra,rank,artist_names,artist_01,artist_02,artist_03,artist_04,artist_05,...,nacionalidad_07,nacionalidad_08,nacionalidad_09,nacionalidad_10,track_name,source,peak_rank,previous_rank,weeks_on_chart,streams
0,Argentina,2025/11/06,noviembre_2025,1,"Roze Oficial, Max Carra, Valen, RAMKY EN LOS C...",Roze Oficial,Max Carra,Valen,RAMKY EN LOS CONTROLES,NaN,...,NaN,NaN,NaN,NaN,Tu jardín con enanitos,Sony Music Uruguay,1,1,24,2468159
1,Argentina,2025/11/06,noviembre_2025,2,"Young Cister, Kreamly",Young Cister,Kreamly,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,QLOO*,Sony Music Entertainment Chile S.A,2,2,19,1671001
2,Argentina,2025/11/06,noviembre_2025,3,Rels B,Rels B,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,TU VAS SIN (fav),DALE PLAY Records / Flakk Team,3,3,16,1522062
3,Argentina,2025/11/06,noviembre_2025,4,"Ovy On The Drums, Quevedo, Beéle",Ovy On The Drums,Quevedo,Beéle,NaN,NaN,...,NaN,NaN,NaN,NaN,YO y TÚ,WEA Latina,4,7,21,1388321
4,Argentina,2025/11/06,noviembre_2025,5,"Jere Klein, Katteyes, Mateo on the Beatz",Jere Klein,Katteyes,Mateo on the Beatz,NaN,NaN,...,NaN,NaN,NaN,NaN,TODO KE VER,2025 JERE KLEIN,3,5,12,1339339

In [31]:
df.shape

(1200, 31)

In [32]:
df.columns

Index(['pais', 'fecha', 'mes_muestra', 'rank', 'artist_names', 'artist_01',
       'artist_02', 'artist_03', 'artist_04', 'artist_05', 'artist_06',
       'artist_07', 'artist_08', 'artist_09', 'artist_10', 'nacionalidad_01',
       'nacionalidad_02', 'nacionalidad_03', 'nacionalidad_04',
       'nacionalidad_05', 'nacionalidad_06', 'nacionalidad_07',
       'nacionalidad_08', 'nacionalidad_09', 'nacionalidad_10', 'track_name',
       'source', 'peak_rank', 'previous_rank', 'weeks_on_chart', 'streams'],
      dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pais             1200 non-null   object
 1   fecha            1200 non-null   object
 2   mes_muestra      1200 non-null   object
 3   rank             1200 non-null   int64
 4   artist_names     1200 non-null   object
 5   artist_01        1200 non-null   object
 6   artist_02        687 non-null    object
 7   artist_03        284 non-null    object
 8   artist_04        103 non-null    object
 9   artist_05        42 non-null     object
 10  artist_06        38 non-null     object
 11  artist_07        20 non-null     object
 12  artist_08        5 non-null      object
 13  artist_09        2 non-null      object
 14  artist_10        2 non-null      object
 15  nacionalidad_01  1200 non-null   object
 16  nacionalidad_02  687 non-null    object
 17  nacionalidad_03  284 non-null    object
 18  nacionalidad_04  103 non-null    object
 19  nacionalidad_05  42 non-null     object
 20  nacionalidad_06  38 non-null     object
 21  nacionalidad_07  20 non-null     object
 22  nacionalidad_08  5 non-null      object
 23  nacionalidad_09  2 non-null      object
 24  nacionalidad_10  2 non-null      object
 25  track_name       1200 non-null   object
 26  source           950 non-null    object
 27  peak_rank        1200 non-null   int64
 28  previous_rank    1200 non-null   int64
 29  weeks_on_chart   1200 non-null   int64
 30  streams          1200 non-null   int64
dtypes: int64(5), object(26)
memory usage: 290.8+ KB

In [34]:
df[["pais", "fecha", "mes_muestra", "rank", "artist_names", "track_name", "streams"]].head()

,pais,fecha,mes_muestra,rank,artist_names,track_name,streams
0,Argentina,2025/11/06,noviembre_2025,1,"Roze Oficial, Max Carra, Valen, RAMKY EN LOS C...",Tu jardín con enanitos,2468159
1,Argentina,2025/11/06,noviembre_2025,2,"Young Cister, Kreamly",QLOO*,1671001
2,Argentina,2025/11/06,noviembre_2025,3,Rels B,TU VAS SIN (fav),1522062
3,Argentina,2025/11/06,noviembre_2025,4,"Ovy On The Drums, Quevedo, Beéle",YO y TÚ,1388321
4,Argentina,2025/11/06,noviembre_2025,5,"Jere Klein, Katteyes, Mateo on the Beatz",TODO KE VER,1339339

In [35]:
artist_cols = [f"artist_{str(i).zfill(2)}" for i in range(1, 11)]

artist_cols

['artist_01',
 'artist_02',
 'artist_03',
 'artist_04',
 'artist_05',
 'artist_06',
 'artist_07',
 'artist_08',
 'artist_09',
 'artist_10']

In [36]:
df_long = df.melt(
    id_vars=["pais", "fecha", "mes_muestra", "rank", "track_name", "streams"],
    value_vars=artist_cols,
    var_name="artist_posicion",
    value_name="artista"
)

df_long.head()

,pais,fecha,mes_muestra,rank,track_name,streams,artist_posicion,artista
0,Argentina,2025/11/06,noviembre_2025,1,Tu jardín con enanitos,2468159,artist_01,Roze Oficial
1,Argentina,2025/11/06,noviembre_2025,2,QLOO*,1671001,artist_01,Young Cister
2,Argentina,2025/11/06,noviembre_2025,3,TU VAS SIN (fav),1522062,artist_01,Rels B
3,Argentina,2025/11/06,noviembre_2025,4,YO y TÚ,1388321,artist_01,Ovy On The Drums
4,Argentina,2025/11/06,noviembre_2025,5,TODO KE VER,1339339,artist_01,Jere Klein

In [37]:
df_long["artista"] = df_long["artista"].astype(str).str.strip()

df_long = df_long[
    (df_long["artista"].notna()) &
    (df_long["artista"] != "") &
    (df_long["artista"] != "NA") &
    (df_long["artista"].str.lower() != "nan")
]

df_long.head()

,pais,fecha,mes_muestra,rank,track_name,streams,artist_posicion,artista
0,Argentina,2025/11/06,noviembre_2025,1,Tu jardín con enanitos,2468159,artist_01,Roze Oficial
1,Argentina,2025/11/06,noviembre_2025,2,QLOO*,1671001,artist_01,Young Cister
2,Argentina,2025/11/06,noviembre_2025,3,TU VAS SIN (fav),1522062,artist_01,Rels B
3,Argentina,2025/11/06,noviembre_2025,4,YO y TÚ,1388321,artist_01,Ovy On The Drums
4,Argentina,2025/11/06,noviembre_2025,5,TODO KE VER,1339339,artist_01,Jere Klein

In [38]:
base_vis = (
    df_long
    .groupby(["artista", "pais"], as_index=False)
    .agg(
        apariciones=("track_name", "count"),
        meses_presente=("mes_muestra", "nunique"),
        streams_total=("streams", "sum")
    )
)

base_vis.head()

       artista      pais  apariciones  meses_presente  streams_total
0        $HUPE    Mexico            5               5       24624878
1    ARIA VEGA  Colombia            4               3        4815546
2    ATL Jacob  Colombia            6               6        4020637
3  AUDREY NUNA     Chile            2               2        1267870
4  AUDREY NUNA    Mexico            1               1        2796068

In [39]:
top_artistas = (
    base_vis
    .groupby("artista", as_index=False)
    .agg(
        apariciones_totales=("apariciones", "sum"),
        paises_distintos=("pais", "nunique"),
        meses_distintos=("meses_presente", "sum"),
        streams_total=("streams_total", "sum")
    )
    .sort_values("apariciones_totales", ascending=False)
    .head(15)
)

top_artistas

,artista,apariciones_totales,paises_distintos,meses_distintos,streams_total
22,Bad Bunny,136,4,24,160529568
27,Beéle,97,3,18,87645187
83,Fuerza Regida,81,4,20,282623107
193,Ovy On The Drums,80,3,18,72198316
31,Blessd,71,3,16,62562542
246,Tito Double P,52,1,6,283595539
201,Peso Pluma,49,1,6,269775448
104,Jere Klein,40,2,11,30774488
117,Junior H,37,1,6,137895311
69,El Bogueto,37,4,22,91994969
272,Yung Beef,37,4,22,91994969
128,Kris R.,37,3,16,34032687
227,Ryan Castro,36,3,13,36476665
14,Anuel AA,35,4,22,51978776
260,Victor Mendivil,31,1,6,142492883

In [40]:
base_vis_top = base_vis[base_vis["artista"].isin(top_artistas["artista"])]

base_vis_top.head()

      artista       pais  apariciones  meses_presente  streams_total
16   Anuel AA  Argentina            9               6        9248166
17   Anuel AA      Chile            9               6        7662216
18   Anuel AA   Colombia           13               6       10926729
19   Anuel AA     Mexico            4               4       24141665
32  Bad Bunny  Argentina           44               6       37449377

In [41]:
base_vis_top.to_csv(
    "base_visualizacion_coincidencias_artistas.csv",
    index=False,
    encoding="utf-8"
)

In [42]:
chart = alt.Chart(base_vis_top).mark_circle().encode(
    x=alt.X(
        "pais:N",
        title="País"
    ),
    y=alt.Y(
        "artista:N",
        title="Artista",
        sort=alt.EncodingSortField(
            field="apariciones",
            op="sum",
            order="descending"
        )
    ),
    size=alt.Size(
        "apariciones:Q",
        title="Apariciones",
        scale=alt.Scale(range=[80, 900])
    ),
    color=alt.Color(
        "apariciones:Q",
        title="Apariciones"
    ),
    tooltip=[
        alt.Tooltip("artista:N", title="Artista"),
        alt.Tooltip("pais:N", title="País"),
        alt.Tooltip("apariciones:Q", title="Apariciones"),
        alt.Tooltip("meses_presente:Q", title="Meses presente"),
        alt.Tooltip("streams_total:Q", title="Streams acumulados", format=",")
    ]
).properties(
    title="Los artistas que cruzan fronteras en los charts latinoamericanos",
    width=650,
    height=450
)

chart

alt.Chart(...)

In [50]:
chart.save("vis_01.html")

In [51]:
!pip install -U altair vl-convert-python -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.0/797.0 kB 12.1 MB/s eta 0:00:00

In [52]:
chart.save("vis_01.jpg")

ValueError: Unsupported format: 'jpg'

In [54]:
chart.save("vis_01.png")

In [55]:
from PIL import Image

img = Image.open("vis_01.png").convert("RGB")
img.save("vis_01.jpg", "JPEG", quality=95)

files.download("vis_01.jpg")